# Generated by Django 5.2.17 on 2026-09-28 18:29

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('\\A[0-9]{10,11}\\Z', 'Use DDD e número: 10 ou 11 dígitos, sem formatação.')])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome', 'id'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='cliente_email_sem_distincao_caixa')],
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.CharField(max_length=120)),
                ('descricao', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta')], default='normal', max_length=10)),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='assistencia.cliente')),
            ],
            options={
                'verbose_name': 'ordem de serviço',
                'verbose_name_plural': 'ordens de serviço',
                'ordering': ['-criado_em', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor_estimado__gte', 0)), name='ordem_valor_nao_negativo'), models.CheckConstraint(condition=models.Q(('status__in', ['aberta', 'em_andamento', 'concluida', 'cancelada'])), name='ordem_status_valido'), models.CheckConstraint(condition=models.Q(('prioridade__in', ['baixa', 'normal', 'alta'])), name='ordem_prioridade_valida')],
            },
        ),
    ]
